"""Bloco 3 do corpus: trechos de dois ou três períodos, 10 a 15 segundos cada.

Existe porque o treino com 15 minutos decorou. Na época 318 o WER do corpus tinha
caído para 11,3% enquanto o de texto novo ficava parado em 39,7% — o modelo
estava ficando ótimo em dizer exatamente as frases gravadas e nada melhor em ler
qualquer outra coisa.

**Por que trechos e não parágrafos longos.** O `collate` do Piper preenche todas
as amostras do batch até a mais longa, então um trecho de 30 s força os outros
sete do batch a 30 s — VRAM desperdiçada numa placa de 6 GB. E na inferência o
Piper quebra o texto por sentença de qualquer forma, então prosódia de parágrafo
inteiro é algo que ele nunca vai usar. Dez a quinze segundos é onde rende mais
minuto por gravação sem pagar nenhum dos dois preços.

**O que se buscou variar,** já que o que faltava era diversidade e não repetição:
diálogo, enumeração, texto técnico, narrativa, opinião, instrução, pergunta
encadeada — cada um com um ritmo diferente. É o ritmo que muda entre eles, não só
as palavras.
"""

from __future__ import annotations

PARAGRAFOS: list[str] = [
    "Cheguei em casa por volta das nove da noite, exausto. A luz da cozinha estava acesa e ninguém tinha lavado a louça do almoço.",
    "Ele me olhou por alguns segundos antes de responder. Disse que não sabia de nada, mas o jeito como falou deixou claro o contrário.",
    "A instalação leva cerca de vinte minutos. Depois disso, basta reiniciar o aparelho e conferir se a luz azul acendeu no painel.",
    "Preciso de três coisas na farmácia: uma caixa de dipirona, dois pacotes de gaze e aquele xarope que você comprou mês passado.",
    "O problema não era o preço, era o prazo. Ninguém conseguiria entregar aquilo em nove dias, por mais que insistissem que sim.",
    "Quando eu era criança, essa rua era de terra batida. Hoje tem asfalto, ciclovia e um posto de gasolina bem na esquina.",
    "Se você apertar o botão duas vezes seguidas, ele entra no modo de configuração. Uma vez só apenas liga ou desliga o aparelho.",
    "A reunião começou atrasada e terminou sem decisão nenhuma. Marcaram outra para sexta, no mesmo horário e com as mesmas pessoas.",
    "Achei estranho que ela não tivesse ligado. Normalmente avisa quando vai demorar, mesmo que seja só uns quinze minutos.",
    "O médico pediu três exames: sangue, urina e um ultrassom abdominal. Disse para levar os resultados na consulta de retorno.",
    "Aquilo mudou completamente a forma como eu enxergava o assunto. Até então eu tinha certeza de estar certo, e não estava.",
    "Deixa eu explicar de outro jeito. Imagina que cada caixa representa um dia, e você precisa encher todas antes do fim do mês.",
    "O ônibus passa de meia em meia hora até as onze. Depois disso, só de hora em hora, e no domingo nem isso é garantido.",
    "Ela abriu a porta devagar, com medo de acordar alguém. A casa inteira estava escura, exceto por uma luz fraca no corredor.",
    "Não adianta reclamar agora que já assinamos. O contrato tem cláusula de fidelidade por doze meses e multa proporcional.",
    "Coloque duas colheres de sopa de farinha, misture bem e deixe descansar por dez minutos antes de levar ao forno.",
    "Foi a melhor decisão que tomei naquele ano. Larguei o emprego numa segunda-feira e na quinta já estava em outra cidade.",
    "O barulho vinha do apartamento de cima e começava sempre à mesma hora. Depois de três semanas, resolvi subir e conversar.",
    "Precisamos revisar o orçamento antes de enviar. Se passar de quinze mil, o cliente vai pedir para cortar alguma coisa.",
    "Ele contou que aprendeu inglês assistindo filmes legendados. Levou uns quatro anos, mas hoje conversa sem dificuldade nenhuma.",
    "A previsão mudou de novo. Agora dizem que a frente fria chega só na quarta-feira, e não na terça como falaram ontem.",
    "Guardei tudo em duas caixas grandes e coloquei no armário do corredor. As fotos ficaram numa pasta separada, na estante.",
    "Você tem razão em parte, mas está esquecendo um detalhe. O prazo só começa a contar depois da homologação, não da assinatura.",
    "O restaurante fica numa travessa pequena, quase escondida. Se você não souber que existe, passa direto sem perceber.",
    "Depois de tantos anos, reencontrar aquela turma foi estranho e bom ao mesmo tempo. Quase ninguém tinha mudado de verdade.",
    "Aperte e segure por cinco segundos até ouvir dois bipes. Solte, espere a luz piscar em verde, e então conecte o cabo.",
    "A conta veio muito mais alta do que o normal. Liguei para a companhia e disseram que houve um erro na leitura do medidor.",
    "Nunca fui de acordar cedo, mas desde que mudei de trabalho não tenho escolha. Levanto às cinco e meia todos os dias.",
    "O filme tem quase três horas e não sobra um minuto. Cada cena serve para alguma coisa, mesmo as que parecem gratuitas.",
    "Antes de sair, confira se as janelas estão fechadas e se o gás está desligado. É sempre nesses dias que acontece alguma coisa.",
    "Ela trabalhou naquele projeto durante oito meses seguidos. Quando finalmente terminou, cancelaram tudo numa reunião de dez minutos.",
    "A vantagem é que não precisa de internet para funcionar. A desvantagem é que qualquer atualização exige conectar por cabo.",
    "Passamos a tarde inteira procurando um lugar para estacionar. No fim deixamos o carro a seis quadras e fomos andando.",
    "Meu pai dizia que ferramenta boa a gente compra uma vez só. Comprei barato duas vezes antes de entender o que ele queria dizer.",
    "O aplicativo pede três permissões: localização, microfone e armazenamento. Só a primeira é realmente necessária para funcionar.",
    "Quando a chuva apertou, todo mundo correu para debaixo da marquise. Ficamos ali uns vinte minutos, conversando sobre nada.",
    "Se a temperatura passar de trinta graus, o sistema desliga sozinho para proteger a placa. Depois religa quando esfria.",
    "Ele nunca reclamou de nada, nem quando teve todos os motivos para reclamar. Acho que era o jeito dele de manter a paz.",
    "Escolhemos a data errada, óbvio. Era feriado prolongado, e metade dos convidados já tinha viajado para o litoral.",
    "A diferença entre os dois modelos é a bateria. Um dura seis horas de uso contínuo, o outro passa das dez sem dificuldade.",
    "Repeti o teste três vezes para ter certeza. Nas três deu o mesmo resultado, então o problema não era aleatório.",
    "Ela cozinhava de memória, sem nunca abrir um caderno de receitas. Dizia que anotar tira o gosto de descobrir o ponto.",
    "O trem atrasou quarenta minutos e ninguém explicou o motivo. Quando finalmente chegou, estava tão cheio que não deu para entrar.",
    "Considere o seguinte: se cada etapa leva dois dias e são sete etapas, você precisa de duas semanas contando os fins de semana.",
    "Tinha uma goiabeira no quintal que dava fruta o ano inteiro. Derrubaram quando ampliaram a garagem, e eu ainda sinto falta.",
    "O erro aparece só depois de umas duas horas rodando. Antes disso tudo funciona normalmente, o que dificulta encontrar a causa.",
    "Levei o cachorro no veterinário porque estava mancando. Era só uma farpa na pata, mas ele ficou dramático o dia inteiro.",
    "Combinamos por mensagem e mesmo assim ela apareceu no lugar errado. Acabamos nos encontrando meia hora depois, na praça.",
    "A pintura descascou por causa da umidade da parede. Não adianta pintar de novo antes de resolver a infiltração por fora.",
    "Ele defendeu o ponto de vista dele com calma, ouviu todos os contra-argumentos e no fim mudou de ideia sem constrangimento nenhum.",
    "O curso tem quarenta horas divididas em oito encontros. As aulas são gravadas, então dá para assistir depois se faltar.",
    "Deixei o café passando e fui tomar banho. Quando voltei, o cheiro tinha tomado a casa inteira e o bule estava vazio.",
    "Se você quiser levar, leve. Só me avise antes, porque preciso saber se ainda posso contar com aquilo no fim de semana.",
    "A rua fica completamente diferente em dezembro. Penduram luzes de um poste ao outro e a padaria abre até mais tarde.",
    "O relatório aponta três causas prováveis, mas descarta duas delas nas conclusões. Sobrou a terceira, que é a mais cara de resolver.",
    "Achei que fosse simples e levei o dia inteiro. No fim descobri que o problema estava numa configuração que eu nem tinha considerado.",
    "Ela tem um jeito próprio de contar história. Começa pelo fim, volta pro meio, e mesmo assim você entende tudo perfeitamente.",
    "Precisamos de uma resposta até quinta-feira. Depois disso a proposta expira e teríamos que recomeçar todo o processo do zero.",
    "O gato fugiu pela janela do banheiro e voltou três dias depois, sujo, magro e absolutamente indiferente ao nosso desespero.",
    "Existem duas formas de fazer isso. A rápida, que funciona quase sempre, e a correta, que funciona sempre mas leva o triplo do tempo.",
    "Fui atendido em cinco minutos, o que foi surpreendente. Normalmente aquela fila leva pelo menos uma hora numa segunda de manhã.",
    "A janela do escritório dá para um pátio interno. Não tem vista nenhuma, mas também não entra barulho da avenida.",
    "Ele guardava recibo de tudo, até de cafezinho. Quando precisou provar uma despesa de dois anos atrás, encontrou em cinco minutos.",
    "Testamos com quatro pessoas diferentes e três tiveram o mesmo problema. Isso já é suficiente para não ser coincidência.",
    "Chegamos cedo demais e ficamos esperando na porta. Abriram quinze minutos atrasados, sem pedir desculpa nem explicar nada.",
    "O sabor lembra alguma coisa da infância, mas não consigo identificar o quê. Talvez algum doce que a minha avó fazia.",
    "Reduza o fogo assim que começar a ferver e mexa de vez em quando. Se deixar no fogo alto, gruda no fundo da panela.",
    "A empresa cresceu rápido demais e não conseguiu acompanhar. Contrataram quarenta pessoas em três meses e dispensaram metade no ano seguinte.",
    "Perguntei se estava tudo bem e ela disse que sim. Pelo tom, claramente não estava, mas não insisti naquele momento.",
    "O manual tem cento e vinte páginas e nenhuma delas explica o que fazer quando a luz vermelha pisca três vezes seguidas.",
    "Foi só depois de voltar que percebi o quanto precisava daquela viagem. Não era cansaço de trabalho, era outra coisa.",
    "Encoste a peça no encaixe e gire no sentido horário até travar. Se não travar, é porque está de cabeça para baixo.",
    "Nunca tinha visto tanta gente naquele parque. Parecia que a cidade inteira tinha decidido sair de casa no mesmo domingo.",
    "O argumento é bom, mas depende de um dado que ninguém verificou. Se aquele número estiver errado, todo o resto desmorona.",
    "Passei três dias tentando consertar sozinho. No quarto dia chamei um técnico, que resolveu em vinte minutos e cobrou barato.",
    "As fotos ficaram escuras porque a luz vinha de trás. Se tivéssemos virado noventa graus, teria ficado bem melhor.",
    "Ele acordava, tomava café, lia o jornal inteiro e só então falava com alguém. Todo mundo em casa respeitava essa ordem.",
    "Preciso confirmar com o time antes de responder. Se depender só de mim, tudo bem, mas isso afeta o cronograma de outras duas pessoas.",
    "A loja fica aberta até as dez da noite durante a semana. No sábado fecha às seis e no domingo nem abre.",
    "Foi engraçado porque todo mundo tinha entendido coisas diferentes da mesma reunião. Só percebemos isso uma semana depois.",
    "O material chegou molhado porque a caixa ficou na chuva. Metade deu para aproveitar, o resto foi perda total.",
    "Prefiro avisar agora do que deixar para amanhã. Se você precisar reorganizar alguma coisa, pelo menos tem tempo de fazer isso.",
    "Havia um piano encostado num canto da sala, cheio de poeira. Ninguém sabia dizer há quanto tempo estava ali.",
    "A atualização corrigiu dois bugs e criou um terceiro. É por isso que muita gente prefere esperar antes de instalar.",
    "Sentamos na varanda e ficamos ali até o sol se pôr completamente. Ninguém falou muita coisa, e estava bom assim.",
    "Comparando os dois orçamentos, a diferença é de quase mil reais. Mas um inclui a instalação e o outro cobra à parte.",
    "Ela decidiu num sábado e na segunda já tinha pedido demissão. Disse que se pensasse demais acabaria não fazendo nunca.",
    "O cheiro de tinta fresca tomou conta do apartamento. Deixamos as janelas abertas dois dias inteiros até passar.",
    "Se der problema, é só desligar da tomada, esperar dez segundos e ligar de novo. Resolve em nove de cada dez casos.",
    "Assisti ao documentário inteiro numa sentada só. São duas horas e vinte, e em nenhum momento passou pela cabeça pausar.",
    "Fizemos uma lista com trinta itens e riscamos vinte e dois. Os oito que sobraram eram justamente os mais complicados.",
    "Naquele apartamento a gente ouvia tudo do vizinho. A televisão, o telefone, e às vezes até a conversa no jantar.",
    "O prazo era apertado, mas a equipe entregou dois dias antes. Ninguém acreditou até ver o sistema funcionando em produção.",
    "Ele tem cinquenta e três anos e voltou a estudar no ano passado. Diz que é a coisa mais difícil que já fez na vida.",
    "Coloque o equipamento numa superfície plana, longe de fontes de calor e com pelo menos dez centímetros livres atrás.",
    "A rua estava tão silenciosa que dava para ouvir o próprio passo. Devia ser umas três da manhã, talvez um pouco mais.",
    "Não é caro se você considerar quanto tempo dura. Comprei o meu há sete anos e nunca precisei de manutenção nenhuma.",
    "Discutimos por quase uma hora sobre uma coisa que os dois concordavam. Só estávamos usando palavras diferentes.",
    "O elevador quebrou de novo, e dessa vez ficou parado quatro dias. Subir onze andares com compras não é experiência agradável.",
    "Ela guardou o bilhete dentro de um livro e esqueceu completamente. Encontrou dez anos depois, mudando de casa.",
    "Comece pelo mais difícil enquanto está descansado. Deixar o pior para o fim do dia é a maneira mais garantida de não fazer.",
    "O resultado saiu na quinta e ninguém foi avisado. Descobrimos por acaso, olhando o site por outro motivo completamente diferente.",
    "Tinha um cheiro bom de comida vindo de algum apartamento. Não dava para saber qual, mas ajudou a passar a fome no caminho.",
    "Se tudo der certo, terminamos até o meio-dia. Se der errado da forma que costuma dar, provavelmente vamos varar a tarde.",
    "Ele repetia a mesma história em todo almoço de família. Ninguém corrigia mais os detalhes que mudavam de uma vez para outra.",
    "A bateria dura o dia inteiro em uso normal. Se você usar câmera e navegação ao mesmo tempo, cai para umas quatro horas.",
    "Voltamos pelo caminho mais longo porque a estrada principal estava interditada. Acabou sendo mais bonito e menos cansativo.",
    "Recebi a mensagem às onze da noite e respondi na manhã seguinte. Pelo visto era urgente, mas ninguém tinha dito isso.",
    "O quadro ficou torto na parede e demorei três dias para reparar. Depois que percebi, não conseguia mais olhar para outra coisa.",
    "São quatro etapas: cadastro, envio dos documentos, análise e assinatura. A terceira é a que costuma travar tudo.",
    "Quando finalmente sentei para escrever, já tinha esquecido metade das ideias. Agora anoto tudo no celular na mesma hora.",
    "A viagem de volta pareceu muito mais curta, como sempre acontece. São exatamente os mesmos quilômetros nas duas direções.",
]
