"""Bloco 2 do corpus: frases longas, gravadas depois do primeiro bloco.

São longas de propósito. O bloco 1 rendeu 95 arquivos e apenas 5 minutos de
áudio, e o que falta para um fine-tune não é quantidade de arquivos, é minutos.

Frase longa também carrega prosódia que frase curta não tem — vírgula,
subordinada, respiração no meio — e é justamente isso que separa uma voz que
lê de uma voz que fala.
"""

from __future__ import annotations

LONGAS: list[str] = [
    "Quando eu saí de casa hoje de manhã ainda estava escuro, e a rua inteira parecia dormir.",
    "Ele explicou que o problema não era o motor, mas uma peça pequena que ninguém tinha percebido.",
    "Se você quiser, posso deixar tudo separado antes de sair, assim você não precisa procurar depois.",
    "A gente combinou de se encontrar às sete, mas ela avisou que talvez chegasse um pouco atrasada.",
    "Depois de muita discussão, decidiram adiar a viagem para o mês seguinte, o que acabou sendo melhor.",
    "Havia uma fila enorme na entrada, então preferimos voltar outro dia com mais calma e paciência.",
    "O médico disse que não era nada grave, mas recomendou repouso e bastante líquido durante a semana.",
    "Meu avô contava que quando era criança precisava caminhar quilômetros até a escola mais próxima.",
    "Não sei se você lembra, mas foi exatamente nesse lugar que a gente se conheceu há alguns anos.",
    "A previsão indica pancadas de chuva no fim da tarde, com trovoadas isoladas e queda de temperatura.",
    "Assim que a energia voltou, percebemos que a geladeira tinha desligado e estragado quase tudo.",
    "Ela guardou aquela carta durante trinta anos sem nunca ter tido coragem de abrir o envelope.",
    "O professor pediu que entregássemos o trabalho até sexta-feira, sem exceção e sem prorrogação.",
    "Quando finalmente conseguimos abrir a porta, descobrimos que a chave estava do outro lado.",
    "Eu preferia resolver isso conversando, mas parece que ninguém está disposto a ceder um pouco.",
    "O trânsito estava tão parado que desistimos do carro e resolvemos ir andando até o centro.",
    "Todas as manhãs ele acorda antes do sol, prepara um café forte e lê o jornal em silêncio.",
    "Ainda que estivesse cansada, ela insistiu em terminar o bordado antes de ir para a cama.",
    "Foi só depois de meia hora procurando que encontrei o documento debaixo de uma pilha de papéis.",
    "A empresa anunciou que vai contratar mais quarenta pessoas até o final do próximo semestre.",
    "Naquela época não existia telefone celular, então combinávamos tudo com uma semana de antecedência.",
    "O cachorro do vizinho fugiu de novo e passamos a tarde inteira procurando por ele no bairro.",
    "Confesso que no começo achei estranho, mas depois de alguns dias me acostumei completamente.",
    "Ele me perguntou se eu tinha certeza, e eu respondi que não, mas que ia tentar mesmo assim.",
    "Colocamos as caixas todas no porão, e agora ninguém lembra em qual delas estão as fotos.",
    "A reunião foi remarcada três vezes, e no fim aconteceu num horário que não servia para ninguém.",
    "Você já reparou como o cheiro de chuva na terra seca traz de volta lembranças muito antigas?",
    "Depois do jantar, costumávamos sentar na varanda e ficar conversando até quase meia-noite.",
    "Se a passagem não estivesse tão cara, eu já teria comprado e ido visitar minha família.",
    "O relatório precisa ser revisado com cuidado, porque qualquer erro ali custa muito caro depois.",
    "Perguntei três vezes e ele continuou dizendo que não sabia de nada sobre aquele assunto.",
    "As crianças ficaram encantadas com os peixes coloridos e não queriam sair do aquário.",
    "Foi um alívio enorme descobrir que o problema era simples e que a solução custava quase nada.",
    "Antigamente essa praça era cheia de árvores, mas cortaram quase todas para alargar a avenida.",
    "Ela aprendeu a tocar violão sozinha, assistindo vídeos e treinando algumas horas por dia.",
    "O time jogou mal no primeiro tempo, mas voltou completamente diferente depois do intervalo.",
    "Não adianta insistir agora, porque a loja já fechou e só abre de novo na segunda-feira.",
    "Guardei o recibo para o caso de precisar trocar, e agora não consigo achar em lugar nenhum.",
    "Havia tanta neblina na estrada que mal dava para enxergar o carro que vinha logo à frente.",
    "Ele trabalhou vinte anos na mesma empresa e se aposentou sem nunca ter faltado um único dia.",
    "Quando o bolo saiu do forno, a casa inteira ficou com aquele cheiro bom de chocolate quente.",
    "Prefiro acordar cedo e resolver tudo de manhã, porque à tarde já não rendo do mesmo jeito.",
    "A menina perguntou por que o céu fica alaranjado no fim do dia, e ninguém soube explicar.",
    "Passamos o feriado arrumando o quintal, e no domingo choveu e desmanchou metade do trabalho.",
    "Se você tivesse me avisado antes, eu teria mudado meus planos e ido junto com vocês.",
    "O ônibus quebrou no meio do caminho e tivemos que esperar quase duas horas por outro.",
    "Ela sempre dizia que paciência era a única coisa que a vida ensina de graça, mas devagar.",
    "Depois de tanto tempo sem se falarem, conversaram como se nada tivesse acontecido.",
    "O aplicativo travou bem na hora de confirmar o pagamento, e a compra não foi registrada.",
    "Deixei uma mensagem na secretária eletrônica, mas até agora ninguém retornou a ligação.",
    "Aquele restaurante pequeno da esquina serve a melhor comida caseira que já provei na vida.",
    "Ele comprou um piano antigo num sebo e passou seis meses restaurando peça por peça.",
    "Precisamos decidir logo, porque quanto mais a gente adia, mais complicado fica resolver.",
    "A viagem foi cansativa, mas valeu cada minuto pela vista que encontramos no topo da montanha.",
    "Não gosto de acordar com despertador, prefiro que a luz do sol entre devagar pela janela.",
    "Todo mundo achou que ia dar errado, e no fim funcionou melhor do que qualquer um esperava.",
    "O barulho da obra começa às sete da manhã e não para até o fim da tarde, todos os dias.",
    "Eu tinha certeza de que havia deixado as chaves na mesa, mas estavam no bolso do casaco.",
    "Ela cozinha sem receita, colocando um pouco de cada coisa até achar que está no ponto certo.",
    "Foi naquele inverno especialmente frio que decidimos finalmente comprar um aquecedor decente.",
    "Se der tudo certo, na semana que vem já teremos o resultado e poderemos seguir em frente.",
    "O livro tem quase novecentas páginas, mas passa tão rápido que dá vontade de recomeçar.",
    "Perdi o horário porque fiquei preso numa ligação que não tinha a menor importância.",
    "As fotografias antigas estavam desbotadas, mas ainda dava para reconhecer todo mundo nelas.",
    "Ele insistiu em pagar a conta inteira, mesmo depois de a gente ter combinado dividir.",
    "Quando abrimos a janela pela manhã, o jardim estava coberto por uma camada fina de orvalho.",
    "A professora explicou de três maneiras diferentes até que todos entendessem o raciocínio.",
    "Não é que eu não queira ir, é que realmente não tenho tempo nenhum essa semana.",
    "Depois de meses tentando, ele conseguiu a vaga e mudou de cidade em menos de duas semanas.",
    "O cheiro de pão fresco vinha da padaria e enchia a rua inteira todas as manhãs bem cedo.",
    "Combinamos que quem chegasse primeiro guardaria lugar para os outros perto da janela.",
    "Ela olhou o relógio, percebeu que estava atrasada e saiu correndo sem nem terminar o café.",
    "Fizemos as contas de novo com calma e descobrimos que tinha faltado somar uma parcela.",
    "Aquele foi o verão mais quente de que se tem notícia, e ninguém conseguia dormir direito.",
    "Ele guardava todas as ferramentas organizadas por tamanho, cada uma no seu lugar exato.",
    "Se continuar chovendo desse jeito, o rio vai transbordar antes mesmo do fim da noite.",
    "A gente ria de coisas bobas, e por algum motivo aquelas tardes ficaram guardadas na memória.",
    "Marquei o dentista para quinta de manhã, então preciso sair do trabalho um pouco mais cedo.",
    "Depois que instalaram o novo semáforo, o trânsito naquele cruzamento melhorou bastante.",
    "Ela escreveu o endereço num guardanapo, e a tinta borrou antes de conseguirmos chegar.",
    "O silêncio da madrugada é tão completo que dá para ouvir o relógio da sala lá de longe.",
    "Levei o computador na assistência e disseram que o conserto sairia mais caro que um novo.",
    "Sempre que viajo, faço questão de andar sem rumo pelo menos uma tarde inteira na cidade.",
    "Ele aprendeu a nadar já adulto, com quarenta anos, depois de perder o medo de água funda.",
    "A gente plantou aquela árvore quando ela nasceu, e hoje já dá sombra no quintal inteiro.",
    "Foi difícil explicar por telefone, então preferi ir até lá e mostrar pessoalmente.",
    "O vendedor garantiu que era o último em estoque, mas eu vi outros três na prateleira.",
    "Passei a manhã inteira organizando arquivos e ainda assim não cheguei nem na metade.",
    "Quando ele finalmente entendeu a piada, todo mundo já tinha mudado de assunto.",
    "A estrada de terra ficava intransitável na chuva, e a vila ficava isolada por dias.",
    "Prometi que ia ligar assim que chegasse, mas o celular descarregou no meio do caminho.",
    "Ela abriu a caixa devagar, com medo do que poderia encontrar depois de tanto tempo.",
    "O ventilador fazia um barulho estranho, e mesmo assim funcionou por mais dois anos.",
    "Se você não gostar, pode trocar sem problema nenhum, é só levar a nota fiscal junto.",
    "A luz do fim de tarde entrava pela cortina e deixava o quarto com um tom dourado.",
    "Discutimos por causa de uma bobagem e ficamos três dias sem nos falar, o que foi ridículo.",
    "Ele contou a história tantas vezes que já ninguém sabia mais o que era verdade nela.",
    "Precisei repetir o endereço duas vezes porque o motorista não entendia o nome da rua.",
    "Naquela manhã de sábado decidimos, sem combinar nada antes, simplesmente pegar a estrada.",
    "O gato dorme exatamente no mesmo lugar do sofá, todo dia, na mesma hora, sem nunca falhar.",
    "Quando percebemos, já era tarde demais para voltar atrás e refazer tudo do começo.",
    "A janela do quarto dava para um pátio interno onde batia sol apenas no fim da manhã.",
    "Ele repetiu a pergunta mais devagar, como se assim ficasse mais fácil de responder.",
    "Trouxeram uma sobremesa que ninguém tinha pedido, e acabou sendo a melhor parte do jantar.",
    "Se eu soubesse que ia demorar tanto, teria levado um livro para passar o tempo.",
    "O papel de parede começou a descolar num canto, e em pouco tempo estava soltando inteiro.",
    "Aprendi mais naquela conversa de quinze minutos do que em vários meses de estudo sozinho.",
    "A cidade muda completamente de aparência depois que as luzes da avenida se acendem.",
]
