"""Monotonic Alignment Search, in place of the Cython extension piper ships.

The Windows wheel of ``piper-tts[train]`` contains only ``setup.py`` and
``__init__.py`` for ``piper.train.vits.monotonic_align`` -- the compiled module
and even the ``.pyx`` source are missing, so training dies at the first batch
with ``No module named piper.train.vits.monotonic_align.monotonic_align``.

This is that algorithm, JIT-compiled with numba instead of Cython. It is the
dynamic programming step at the heart of VITS: given the cost of aligning every
text position with every audio frame, find the single monotonic path through the
grid with the lowest total cost -- which is how the model learns, without any
labelled alignment, how long each phoneme lasts.

``install()`` writes a tiny module into site-packages pointing back here, so
piper finds it under the name it expects.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from numba import njit, prange

MAX_NEG = -1e9


@njit(cache=True)
def _path_for_one(path, value, t_y, t_x):
    """Fill one alignment path in place, forward pass then backtrace."""
    index = t_x - 1

    for y in range(t_y):
        # Only the diagonal band is reachable: a monotonic path cannot skip
        # ahead of the text or fall so far behind that it can never catch up.
        for x in range(max(0, t_x + y - t_y), min(t_x, y + 1)):
            current = MAX_NEG if x == y else value[y - 1, x]
            if x == 0:
                previous = 0.0 if y == 0 else MAX_NEG
            else:
                previous = value[y - 1, x - 1]
            value[y, x] += max(previous, current)

    for y in range(t_y - 1, -1, -1):
        path[y, index] = 1
        if index != 0 and (index == y or value[y - 1, index] < value[y - 1, index - 1]):
            index -= 1


@njit(parallel=True, cache=True)
def maximum_path_c(paths, values, t_ys, t_xs):
    """Signature piper expects: fills ``paths`` in place, one entry per batch."""
    for i in prange(paths.shape[0]):
        _path_for_one(paths[i], values[i], t_ys[i], t_xs[i])


SHIM = '''"""Auto-generated by lab.finetune.monotonic_align -- do not edit.

The Windows wheel of piper-tts ships this package without its compiled
extension. This forwards to the numba implementation in the project.
"""

from lab.finetune.monotonic_align import maximum_path_c  # noqa: F401
'''


def install() -> bool:
    """Create the module piper imports, if it is missing. Returns True if written.

    Locates the folder through the parent package: importing
    ``monotonic_align`` itself is what fails, so asking for it would be circular.
    """
    import piper.train.vits as vits

    target = Path(vits.__file__).parent / "monotonic_align" / "monotonic_align"
    core = target / "core.py"
    if core.exists():
        return False

    target.mkdir(parents=True, exist_ok=True)
    (target / "__init__.py").write_text("", encoding="utf-8")
    core.write_text(SHIM, encoding="utf-8")
    return True


def selftest() -> None:
    """Check the path is monotonic and covers every frame -- the two invariants."""
    rng = np.random.default_rng(0)
    t_y, t_x = 40, 12
    value = rng.standard_normal((1, t_y, t_x)).astype(np.float32)
    path = np.zeros((1, t_y, t_x), dtype=np.int32)
    maximum_path_c(path, value, np.array([t_y], np.int32), np.array([t_x], np.int32))

    picked = path[0].argmax(axis=1)
    assert path[0].sum() == t_y, "cada frame precisa de exatamente um simbolo"
    assert np.all(np.diff(picked) >= 0), "o caminho tem que ser monotonico"
    assert picked[0] == 0 and picked[-1] == t_x - 1, "precisa cobrir do primeiro ao ultimo"
    print(f"  ok: caminho monotonico, {t_y} frames sobre {t_x} simbolos")


if __name__ == "__main__":
    print("instalado" if install() else "ja estava instalado")
    selftest()
